Mobilefirst toolbar headline section
pushkar1995/portfolio-website pull request #1
Opened 2023-06-02 13:25 UTC by pushkar1995

Mobilefirst task to create the Header and Headline Section is completed and pushed for review.

2023-06-02 15:37 UTC, osamaashraf6 requested changes
Hi @pushkar1995 😊, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![SoCloseAlmostGIF (3)](https://github.com/Graceshiks/Portfolio-MobileFirst/assets/83360636/42e92e8b-3a1d-4ba7-8cf7-86c4d258ee97)

## Highlights 🎉🎉
- [ ] Following Figma design😊👌
- [ ] Use the semantics elements💯
- [ ] Nice design .🚀
- [ ] Use the flexbox to place the items 😃👍

## Required Changes ♻️

- [ ]  Please 😊 consider using best practices when you write commit messages, they should be capitalized sentences in the imperative form, for example: "Fix bug at CSS file" instead of " fixed or fixing Bug in CSS file"  ... etc 👍

_Check the comments under the review._

## Optional suggestions
- N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-02 15:37 UTC, osamaashraf6 commented on style.css
> +  background-attachment: fixed;
- [ ] Kindly😊 try to place the background image of this section at the correct place as you see the correct place for it is in the bottom right of the page, but in your case, it is not at the correct place, so let's fix that by putting it in the correct place like the Figma Design 💯🚀
- [ ] Also 😃I see that there is a part of the background image is not appearing on the page, so please try to put all the background images as expected like the Figma Design to make the design nice like the Figma 💯🚀

> Check below to see the difference 😊⤵️
> If you can not see the image clearly just click on it to open a new tab in the browser😊

| Original design | Your design| 
| --- | --- |
|   ![image](https://github.com/pushkar1995/portfolio-website/assets/83360636/9ffcb236-3d54-495f-b0e0-94231fbc9c92) |    ![image](https://github.com/pushkar1995/portfolio-website/assets/83360636/eb420e54-6759-4464-95ff-368aaa519fe2) |

2023-06-02 15:37 UTC, osamaashraf6 commented on style.css
> +}
- [ ] Kindly 😊 try to remove the unnecessary comment here because this makes your codebase ugly, we want your code to look nice now and in the next projects try to not put unnecessary comments in the base code to make the code organized and nice for the others😃

2023-06-02 18:46 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle: 

Hi @pushkar1995, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-02 18:46 UTC, Qoosim commented on style.css
> +  background-attachment: fixed;
- [ ] As mentioned by the previous reviewer, your background image is yet to be positioned properly. Kindly look into it and fix.

### Your Design
![your-design](https://github.com/pushkar1995/portfolio-website/assets/26597432/f48e2b35-1b10-49b0-87bf-0938968c0927)

### Figma Design
![temp-design](https://github.com/pushkar1995/portfolio-website/assets/26597432/a42d2220-e6fa-4a56-aac6-5893e4813161)

2023-06-02 20:09 UTC, pushkar1995 commented
@Qoosim @osamaashraf6  Please review my code. For this review, I have tried my best to fix the review earlier mentioned.

2023-06-02 20:24 UTC, shahadat3669 requested changes
Hi @pushkar1995 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

<img src="https://media1.giphy.com/media/jmqAUNFXAElgafPK0g/giphy.gif"/>

## Invalid Code Review Request

You have submitted a project, Where you should have a new PR for a new feature. As per the project requirement, your new feature is **[Portfolio: finish the mobile version](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md)**.  Please follow **[Github flows](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md)** as it also included in the project requirement.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-02 21:30 UTC, pushkar1995 commented
@Qoosim @shahadat3669 @osamaashraf6 does this mean that I have changed more than asked in the code review? Actually I was no aware about the github flow.As I was researching and learning figma and css while doing this project, I knew little bit about figma but while doing this project it felt like I understand what should be done as I learned more about figma and the relation of figma and css so I did what I felt right doing with the code for the mobile first design.I guess this was my mistake for the the PR and Review request.So please suggest me, now to fix this do I need to go back to the previous review commit and fix the mentioned review only for the position of the image in the headline background?

2023-06-03 09:05 UTC, TadesseDev requested changes
### Hi @pushkar1995 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![199733072-bdacca19-8df9-43a7-be93-3aff2f1c15c8](https://user-images.githubusercontent.com/69077061/204107907-c2532abb-b23d-4fda-88f0-1ec9c7b71971.gif)

 ## Highlights
 - [x] Good job making most of the changes requested by the previous reviewer. 🙏


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 09:05 UTC, TadesseDev commented on index.html
> +        </a>
- [ ] Dear @pushkar1995, I have seen your previous comments and I just wanna assure you that you are doing great. Your project is 95% there. The only main problem I see is, as suggested previously, Your decoration image should be a background image instead of an `<img>` tag. This is because your background image would overflow over the text. The other benefit is since the decoration image does not provide important information to the SEO (Search Engine Optimization), hence making it a background image makes sense. Please consider making your decoration image a background image.
- [Optional] Also, I notice your social media icons are a bit blurred compared to the original design. Please try to address this too.   

-[Optional] One last thing is. when you apply images, Please use the `./` to refer to the relative path than the `/`. this way your picture will always be addressed correctly (both locally and online).

### Your design 
![image](https://github.com/pushkar1995/portfolio-website/assets/69077061/3bf6aad0-6a13-4f65-893f-32d6188a33b3)

### Figma design 
![image](https://github.com/pushkar1995/portfolio-website/assets/69077061/6eeb7c70-5867-48a8-9ea2-3470363cd1a5)

2023-06-03 12:43 UTC, pushkar1995 commented
@Qoosim @shahadat3669 @TadesseDev @osamaashraf6 I think I fixed everything that needs fixing for this PR so please review and approve.

2023-06-03 13:04 UTC, bobb-Rob approved these changes
## STATUS: APPROVED ✔️ 🍾 🍾 🍾 🥳 🥳 🥳 

Hi @pushkar1995, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages

## Optional suggestions

This is optional because the previous reviewer did not mention it, but I recommend that you implement it. The space between the navbar and the `Hey there` text is too much. kindly reduce and ensure it is `120px`.

![image](https://github.com/pushkar1995/portfolio-website/assets/84156714/fba44132-da86-434e-b061-4699c6354cc0)


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 13:07 UTC, merged